default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DB'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DB'] %>

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DB'] %>
